spring.application.name=aplicativo-gestao-treino

spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#configuracoes JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#configuracoes Liquibase
spring.liquibase.change-log=classpath:/liquibase/master.xml
