url=jdbc:mysql://localhost:3306/FITAPP?useTimezone=true&serverTimezone=UTC
username=root
password=admin123
driver=com.mysql.cj.jdbc.Driver
referenceUrl=hibernate:spring:dev.aplicativo_gestao_treino?dialect=org.hibernate.dialect.MySQL8Dialect
verbose=true
logging=debug

changeLogFile=src/main/resources/liquibase/master.xml
